export const INDIGO = '#3730A3';

export const lightColors = {
  INDIGO,
  background: '#EEF2FF',
  card: '#ffffff',
  title: '#111827',
  subtitle: '#6B7280',
  label: '#374151',
  inputBg: '#F9FAFB',
  inputBorder: '#E5E7EB',
  inputText: '#111827',
  placeholder: '#9CA3AF',
  logoText: '#1E1B4B',
  socialBorder: '#E5E7EB',
  socialBg: '#ffffff',
  socialText: '#111827',
  socialIconColor: '#000000',
  dividerLine: '#E5E7EB',
  dividerText: '#9CA3AF',
  footerText: '#6B7280',
  iconColor: '#9CA3AF',
  statusBar: 'dark',
  sectionTitle: '#111827',
  pillActiveBg: INDIGO,
  pillActiveText: '#ffffff',
  pillInactiveBg: '#ffffff',
  pillInactiveText: '#374151',
  pillInactiveBorder: '#E5E7EB',
  venueBg: '#ffffff',
  venueBorder: '#F3F4F6',
  venueSubtext: '#6B7280',
  starColor: '#F59E0B',
  seeAllColor: INDIGO,
  navBg: '#ffffff',
  navBorder: '#E5E7EB',
  navActive: INDIGO,
  navInactive: '#9CA3AF',
  confirmedBadgeBg: INDIGO,
  confirmedBadgeText: '#ffffff',
  bookingMetaBg: '#F9FAFB',
  bookingMetaLabel: '#6B7280',
  bookingMetaValue: '#111827',
  pastItemBorder: '#F3F4F6',
  logoutColor: '#EF4444',
  settingsRowBg: '#ffffff',
  settingsBorder: '#F3F4F6',
};

export const darkColors = {
  INDIGO,
  background: '#0F0F1A',
  card: '#1E1E2E',
  title: '#F9FAFB',
  subtitle: '#9CA3AF',
  label: '#D1D5DB',
  inputBg: '#2A2A3E',
  inputBorder: '#374151',
  inputText: '#F9FAFB',
  placeholder: '#6B7280',
  logoText: '#E0E7FF',
  socialBorder: '#374151',
  socialBg: '#2A2A3E',
  socialText: '#F9FAFB',
  socialIconColor: '#F9FAFB',
  dividerLine: '#374151',
  dividerText: '#6B7280',
  footerText: '#9CA3AF',
  iconColor: '#6B7280',
  statusBar: 'light',
  sectionTitle: '#F9FAFB',
  pillActiveBg: INDIGO,
  pillActiveText: '#ffffff',
  pillInactiveBg: '#2A2A3E',
  pillInactiveText: '#D1D5DB',
  pillInactiveBorder: '#374151',
  venueBg: '#1E1E2E',
  venueBorder: '#2A2A3E',
  venueSubtext: '#9CA3AF',
  starColor: '#F59E0B',
  seeAllColor: '#818CF8',
  navBg: '#1E1E2E',
  navBorder: '#2A2A3E',
  navActive: '#818CF8',
  navInactive: '#6B7280',
  confirmedBadgeBg: INDIGO,
  confirmedBadgeText: '#ffffff',
  bookingMetaBg: '#2A2A3E',
  bookingMetaLabel: '#9CA3AF',
  bookingMetaValue: '#F9FAFB',
  pastItemBorder: '#2A2A3E',
  logoutColor: '#F87171',
  settingsRowBg: '#1E1E2E',
  settingsBorder: '#2A2A3E',
};
